repositories {
    mavenLocal()
    mavenCentral()
    maven { // BungeeCord Repository
        url = 'https://oss.sonatype.org/content/repositories/snapshots'
    }
    maven { // Paper Repository (for Brigadier snapshot)
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    api project(":api")

    compileOnly "net.md-5:bungeecord-api:$bungeecordVersion"
}
